FROM phusion/baseimage:latest

MAINTAINER Michael Bishop <m@aquariusinteractive.com>
 
RUN apt-get update &&  apt-get -y upgrade && apt-get -y dist-upgrade && apt-get install memcached

CMD memcached


